ingress:
  tls:
    enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "${ingressClass}"
    # https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/
    nginx.ingress.kubernetes.io/auth-url: "https://${oauthExternalAuthHost}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://${oauthExternalAuthHost}/oauth2/start?rd=https://$host$request_uri"