{{- if eq .Values.clusterIssuer.challengeProvider "cloudflare" }}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: "{{ .Values.clusterIssuer.letsEncryptEmail }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: "{{ .Values.clusterIssuer.letsEncryptEmail }}"
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
{{- end }}