{{- if eq .Values.clusterIssuer.challengeProvider "digitalocean" }}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: digitalocean-issuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: "{{ .Values.clusterIssuer.letsEncryptEmail }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-digitalocean
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
{{- end }}