# Enable the HTTP-01 challenge provider
{{- if eq .Values.clusterIssuer.challengeProvider "http01" }}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: "{{ .Values.clusterIssuer.letsEncryptEmail }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      # Enable the HTTP-01 challenge provider
      - http01:
          ingress:
            class: "{{ .Values.clusterIssuer.http01.ingressClass }}"
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: "{{ .Values.letsEncryptEmail }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      # Enable the HTTP-01 challenge provider
      - http01:
          ingress:
            class: "{{ .Values.clusterIssuer.http01.ingressClass }}"
{{- end }}