# Enable the HTTP-01 challenge provider
{{- $letsEncryptEmail := .Values.clusterIssuer.letsEncryptEmail -}}
{{- if eq .Values.clusterIssuer.challengeProvider "http01" }}
{{- range $class := .Values.clusterIssuer.http01.ingressClass }}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ $class }}-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: "{{ $letsEncryptEmail }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-{{ $class }}-staging
    solvers:
      # Enable the HTTP-01 challenge provider
      - http01:
          ingress:
            class: "{{ $class }}"
{{- end }}
---
{{- range $class := .Values.clusterIssuer.http01.ingressClass }}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ $class }}-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: "{{ $letsEncryptEmail }}"
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-{{ $class }}-prod
    solvers:
      # Enable the HTTP-01 challenge provider
      - http01:
          ingress:
            class: "{{ $class }}"
{{- end }}
{{- end }}