controller:
  podLabels:
    app: ingress-nginx

  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - ingress-nginx
      topologyKey: "kubernetes.io/hostname"
  
  metrics:
    enabled: true

    serviceMonitor:
      enabled: true
      scrapeInterval: 10s
      namespace: monitoring
      additionalLabels:
        release: prometheus-operator

defaultBackend: {}