grafana:
  grafana.ini:
    auth.gitlab:
      enabled: ${enabled}
      allow_sign_up: true
      client_id: ${clientID}
      client_secret: ${clientSecret}
      scopes: api
      auth_url: https://gitlab.com/oauth/authorize
      token_url: https://gitlab.com/oauth/token
      api_url: https://gitlab.com/api/v4
      allowed_groups: lazyorangejs