# https://github.com/helm/charts/issues/19928#issuecomment-580403978
prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false

  tlsProxy:
    enabled: false

  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

prometheus:
  ingress:
    enabled: true
    hosts:
    - ${prometheus_url}
    tls:
    - hosts:
      - ${prometheus_url}
      secretName: prometheus-tls
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "${ingress_class}"

  resources:
    requests:
      memory: 400Mi