prometheusOperator:
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

prometheus:
 resources:
    requests:
      memory: 400Mi

# https://github.com/helm/charts/tree/master/stable/grafana#configuration
grafana:
  # dashboards:
  #   # https://github.com/kubernetes/ingress-nginx/tree/master/deploy/grafana/dashboards
  #   ingress-nginx:
  #     url:
  # https://grafana.com/docs/grafana/latest/auth/gitlab/#enable-gitlab-in-grafana
  grafana.ini:
    server:
      root_url: https://${grafana_url}
    paths:
      data: /var/lib/grafana/data
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console
    
    grafana_net:
      url: https://grafana.net

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingress:
    hosts:
    - ${grafana_url}
    tls:
    - hosts:
      - ${grafana_url}
      secretName: grafana-tls
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "${ingressClass}"