# https://github.com/helm/charts/tree/master/stable/grafana#configuration
# https://github.com/helm/charts/tree/master/stable/grafana#import-dashboards
grafana:
  defaultDashboardsEnabled: true
  #
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      nodejs:
        # Ref: https://grafana.com/grafana/dashboards/11159
        gnetId: 11159
        revision: 1
        datasource: Prometheus
      redis:
        # Ref: https://grafana.com/grafana/dashboards/11835/reviews
        gnetId: 11835
        revision: 1
        datasource: Prometheus
      kong:
        # Refs: 
        # - https://grafana.com/grafana/dashboards/7424
        # - https://docs.konghq.com/hub/kong-inc/prometheus/
        gnetId: 7424
        revision: 6
        datasource: Prometheus
  #   # https://github.com/kubernetes/ingress-nginx/tree/master/deploy/grafana/dashboards
  #   ingress-nginx:
  #     url:
  # https://grafana.com/docs/grafana/latest/auth/gitlab/#enable-gitlab-in-grafana
  grafana.ini:
    server:
      root_url: https://${grafana_url}
    paths:
      data: /var/lib/grafana/data
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console
    
    grafana_net:
      url: https://grafana.net

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  ingress:
    hosts:
    - ${grafana_url}
    tls:
    - hosts:
      - ${grafana_url}
      secretName: grafana-tls
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "${ingressClass}"