debug: true

ingress:
  extraAnnotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"

    kubernetes.io/ingress.class: ${ingressClass}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: ${clusterIssuer}